#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me is redirecting to another page

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
