#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 and
# display FizzBuzz when the number is a multiple of 3 and 5
# Fizz when it's a multiple of 3 and
# Buzz when it's a multiple of 5

i=0
while [ $((i++)) -lt 100 ]; do
	if [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo $i
	fi
done
