#!/usr/bin/env bash

# This script loops from 1 to 10 and
# display "bad luck" for the 4th loop iteration
# "good luck" for the 8th one
# and "Best School" for the others

i=0
while [ $((i++)) -lt 10 ]; do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
