#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 and
# display 4 and then "bad luck from China" for the 4th loop iteration
# 9 and then "bad luck from Japan" for the 9th one
# 17 and then "bad luck from Italy" for the 17th one

i=0
while [ $((i++)) -lt 20 ]; do
	echo $i
	case $i in 4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	esac
done
