#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes

h="-1"
while [ $((h++)) -lt 12 ]; do
	echo Hour: $h
	min="0"
	while [ $((min++)) -lt 59 ]; do
		echo $min
	done
done
